### ISSUE TITLE
incorrect display

### ISSUE THREAD

**Issue by liuxilu** [DeltaNedas/ldb#1]
- On 6.0 release 125
- A new sandbox game with the map Fork
- A processor on the top of the core
- Click the processor then the arrow
<details><summary>image</summary>

![image](https://user-images.githubusercontent.com/53636947/108302831-bc8dfe00-71df-11eb-8025-aebb968ab9b6.png)
</details>

- Change `table.add(this.table).size(300, 300).bottom().colspan(2);`
to `table.add(this.table).size(300, 100).bottom().colspan(2);` and again

<details><summary>image</summary>

![image](https://user-images.githubusercontent.com/53636947/108303357-bcdac900-71e0-11eb-9912-772ad1723e32.png)
</details>

**Comment by deltanedas** [comment]
1. that doesnt hide the black line
2. when there are variables, it's painful to scroll through them 3 at a time

**Comment by liuxilu** [comment]
W...What? There should be a block displaying variables but only a black line now.
