### ISSUE TITLE
The menu shows nothing

### ISSUE THREAD

**Issue by SMOLKEYS** [DeltaNedas/ldb#5]
Everytime i open the debug menu i get this

![Screenshot_20210517-135813_Mindustry](https://user-images.githubusercontent.com/75618732/118439189-0b343100-b718-11eb-874c-843c0e6b6d5a.jpg)

Its just offset and blank

**Comment by SMOLKEYS** [comment]
Well, it does work, but not really well

![Screenshot_20210517-150752_Mindustry.jpg](https://user-images.githubusercontent.com/75618732/118446247-fd83a900-b721-11eb-8cc5-3902c10651de.jpg)

**Comment by SMOLKEYS** [comment]
I can only move it left and right but not up and down

**Comment by deltanedas** [comment]
1. that is caused by you not compiling anything, so there are no variables stored, **invalid**
2. you dont have enough variables for the scrollbar to be enabled.
i should probably try to fix the weird offset that hides most variables

**Comment by SMOLKEYS** [comment]
> you dont have enough variables for the scrollbar to be enabled.

yeah, i saw that

> i should probably try to fix the weird offset that hides most variables

this is my issue

**Comment by SMOLKEYS** [comment]
anyways

**Comment by SMOLKEYS** [comment]
ill be waiting

![SmartSelect_20210520-230133_Chrome](https://user-images.githubusercontent.com/75618732/119002372-6471be00-b9bf-11eb-8cd5-c8a516f805e6.jpg)
