### ISSUE TITLE
Resetting processor with no code crashes Mindustry

### ISSUE THREAD

**Issue by eliminmax** [DeltaNedas/ldb#8]
I just installed this mod, and tried it out in a sandbox world. I placed down a hyper processor, clicked the reset button, out of curiosity, and Mindustry instantly crashed. A micro processor without any code had the same result. Adding a simple pair of `draw` and `drawflush` commands and attaching a display was enough to prevent the crash.

Edit: it did not reset after removing previously existing code, then resetting.

**System info, in case it's relevant:**
OS: Pop!_OS 20.04 (Linux, fork of Ubuntu)
Mindustry version: release build 126.2
Mod version: v1.3.2
Other Mods: 
* [Anuke Logic](https://github.com/DeltaNedas/anuke-logic) v1.9.3
* [Override Lib](https://github.com/DeltaNedas/override-lib) v1.0.1
* [RTFM](https://github.com/DeltaNedas/rtfm) v2.14.10
* [UI Lib](https://github.com/DeltaNedas/ui-lib) v2.16.6
* Installed, but disabled: [Testing Utilities](https://github.com/MEEPofFaith/testing-utilities) v0.14

**Crash reports:**
[crash-report-06_12_2021_17_08_53.txt](https://github.com/DeltaNedas/ldb/files/6642904/crash-report-06_12_2021_17_08_53.txt)
[crash-report-06_12_2021_17_13_31.txt](https://github.com/DeltaNedas/ldb/files/6642905/crash-report-06_12_2021_17_13_31.txt)

**Error Message:**
![mindcrash](https://user-images.githubusercontent.com/33302691/121789165-af878700-cba1-11eb-9800-6a705046aef4.png)

**Sandbox Setup:**
![mindsetup](https://user-images.githubusercontent.com/33302691/121789457-2291fd00-cba4-11eb-8d0b-719e2933cca0.png)
The hyper processor has the following code in it:
```
draw clear 0 0 0 0 0 0
drawflush display1
```

**Comment by rodrigolitzius** [comment]
that's happening to me too. on  Windows and Mobile
