### ISSUE TITLE
Display is offset, hides variables.

### ISSUE THREAD

**Issue by S1ndr0m3** [DeltaNedas/ldb#9]
I am on mobile. When I click the dropdown menu it cuts off the top lines and makes it difficult to use.
![Screenshot_20210706-104154](https://user-images.githubusercontent.com/87029694/124629761-5a106400-de47-11eb-9ea4-214a5738da40.png)
![Screenshot_20210706-104209](https://user-images.githubusercontent.com/87029694/124629765-5aa8fa80-de47-11eb-8034-1ab0ab02d83e.png)

**Comment by S1ndr0m3** [comment]
If there are enough variables in the logic code the variable display window gets bigger. But once you remove enough variable sets, the top of the display goes down, instead of the bottom going up.![Screenshot_20210811-075737.png](https://user-images.githubusercontent.com/87029694/129033789-611fe6ab-a941-4443-bc93-b7bd2183d28d.png)![Screenshot_20210811-075815.png](https://user-images.githubusercontent.com/87029694/129033809-9efbdcec-6290-4e39-a18d-25f92a8bba03.png)![Screenshot_20210811-075847.png](https://user-images.githubusercontent.com/87029694/129033822-4d6f4814-cbb6-4265-8db2-9ec709973df3.png)![Screenshot_20210811-075414.png](https://user-images.githubusercontent.com/87029694/129033832-44e7589b-e7e7-4efa-8dd1-596c72d1eb47.png)

**Comment by kontikusho** [comment]
Maybe resolution is involved.

HD+(1480×720)
![Screenshot_20210904-124354_Mindustry.jpg](https://user-images.githubusercontent.com/6623081/132081376-d3c058b1-4e6c-4da0-8299-6e28e05dae2b.jpg)

FHD+(2220×1080)
![Screenshot_20210904-124308_Mindustry.jpg](https://user-images.githubusercontent.com/6623081/132081420-0cb356ec-9226-41b2-850e-7fe69dcc8541.jpg)

**Comment by S1ndr0m3** [comment]
Nice catch. Its definitely a resolution issue. The problem goes away when my phone is on the lowest resolution. Unfortunately, all of the in game menus now crowd the screen. :/

**Comment by kontikusho** [comment]
#11

**Comment by kontikusho** [comment]
Made scrollable element same size as outer element.
